### ISSUE TITLE
 Failed to parse XXXXXXXX.nonces

### ISSUE THREAD

**Issue by GIACOMO-JPG** [AloneLiberty/FlipperNestedRecovery#1]
It worked several times but recently started giving this error

![immagine](https://user-images.githubusercontent.com/70541828/232203138-66627df3-ced1-479b-84fc-329789d8ed96.png)

**Comment by AloneLiberty** [comment]
Try collecting nonces again (run Nezted attack). If it still doesn't work, upload this file from /ext/nfc/.nested/ and send here.

**Comment by GIACOMO-JPG** [comment]
here is the file I opened it with a textedit but inside there is only this string of text 
[2EF741B5.zip](https://github.com/AloneLiberty/FlipperNestedRecovery/files/11239183/2EF741B5.zip)
```
Note: you will need desktop app to recover keys: https://github.com/AloneLiberty/FlipperNestedRecovery
Version: 2
```
it's normal?

**Comment by AloneLiberty** [comment]
No nonces collected. Maybe you already found all keys or you skipped nonce collection part.

**Comment by awnyel** [comment]
im having same issue but im doing all as you saind in docs
