### ISSUE TITLE
Bug: When `(Ignoring Sum(a8) properties)` multithreading no longer seems to work

### ISSUE THREAD

**Issue by Masqueey** [AloneLiberty/FlipperNestedRecovery#11]
Sorry for bothering you again. Whenever I hit `(Ignoring Sum(a8) properties)` in cracking, it seems the states get bruteforced using only one thread. Otherwise all, in my case 8, threads get used, this seems to be an exception.

**Comment by AloneLiberty** [comment]
Not mine bug, belongs to https://github.com/RfidResearchGroup/proxmark3.
And not critical any way, you could of course send nonces here, but I can't guarantee I'll check it or do anything with it.

**Comment by Masqueey** [comment]
Thanks I'll reach out to them!
