### ISSUE TITLE
 having trouble running "FlipperNested" in Terminal.

### ISSUE THREAD

**Issue by TomShook1** [AloneLiberty/FlipperNestedRecovery#15]
Hello,
I am having trouble running "FlipperNested" in Terminal.
I typed: python -m FlipperNested
and nothing happens.
No error message saying that the file does not exist, nothing.
Wondering if someone could help.

Update:
when the Flipper is not plugged in and I try to execute, the terminal spits out "Flipper missing" message.
when qFlipper is open (and flipper is connected) and I try to execute, it gives me a permission error.
Please help
Thanks.
(I'm VERY new to this)

**Comment by AloneLiberty** [comment]
> when the Flipper is not plugged in and I try to execute, the terminal spits out "Flipper missing" message.
> when qFlipper is open (and flipper is connected) and I try to execute, it gives me a permission error.

Maybe because you need to connect Flipper and don't open qFlipper?

**Comment by TomShook1** [comment]
> Maybe because you need to connect Flipper and don't open qFlipper?

That's what I tried first per directions, Nothing happens. I just want to see if anything would happen if qflipper WAS open.

**Comment by AloneLiberty** [comment]
Explain what you mean with nothing happens. It just ends without any output? Have you collected nonces before running it?

**Comment by TomShook1** [comment]
> Explain what you mean with nothing happens. It just ends without any output? Have you collected nonces before running it? 

I figured it out a couple of days ago and forgot to update my post. The nonces didn't save properly on my flipper, and I had to recollect the nonces..
