### ISSUE TITLE
it seems to be no echo after execution on M1 Mac

### ISSUE THREAD

**Issue by missuo** [AloneLiberty/FlipperNestedRecovery#20]
<img width="697" alt="image" src="https://github.com/AloneLiberty/FlipperNestedRecovery/assets/55200481/236a955f-1542-4647-9789-d86ed63eb7c8">

**Comment by AloneLiberty** [comment]
Probably you don't have nonces for that UID or you misspelled it. As plain `FlipperNested` doesn't give you anything, you don't have any nonces at all
