### ISSUE TITLE
Request for Guidance on Creating a Standalone Executable for FlipperNested

### ISSUE THREAD

**Issue by oldip** [AloneLiberty/FlipperNestedRecovery#24]
I am developing a GUI version of FlipperNested aimed at enhancing usability for those less familiar with command-line tools. My primary goal is to package the command-line tool into a standalone executable with PyInstaller, enabling it to be run on Windows machines directly from the command prompt without installing Python or any dependencies.

Despite my efforts, I have encountered significant challenges in packaging the tool, particularly with ensuring that all dependencies are correctly included in the single executable file. Here are the specific issues I need help with:

1. PyInstaller Configuration: I am unsure how to properly configure PyInstaller to include all the necessary dependencies and Python files into the executable.
2. Executable Functionality: After packaging, the generated .exe file does not execute as expected when run from the command prompt, showing no output or errors.
Could you provide any advice or steps on how to successfully create a fully functional .exe for FlipperNested? Additionally, if there are any specific considerations or recommendations for integrating the command-line functionality into a GUI application, that information would also be greatly appreciated.

Thank you very much for your assistance and for the great work on FlipperNested. I look forward to making it more accessible to a wider audience.

**Comment by oldip** [comment]
I wanted to follow up on my previous issue regarding building a standalone executable for FlipperNested on Windows. I've encountered additional challenges and would greatly appreciate your assistance.

Current Challenges:

Cross-Platform Compatibility: I successfully built the Python package on Linux, but the resulting .whl file isn't compatible with Windows. When I tried building directly on Windows, I ran into multiple compilation errors, especially related to missing libraries like pthread and lzma. I've attempted to resolve these by manually adding the libraries, but this has led to other issues, such as unsupported functions like fmemopen.

Real-Time Progress Display: For the GUI I'm developing, it's crucial to have real-time progress updates. However, the default behavior in HardNestedSolver\pm3\ui.c sets flushAfterWrite to false, which prevents my GUI from displaying progress in real-time. I would need this setting to be true for the GUI to function correctly.

Help Needed:

Windows-Compatible Build: Is there any way to obtain a prebuilt .whl package for Windows where flushAfterWrite is set to true in the ui.c file? This would allow me to proceed with integrating real-time progress updates into the GUI without needing to resolve all the Windows-specific build issues.

Guidance on Building for Windows: If a prebuilt package isn't feasible, could you provide guidance on resolving the compilation issues I'm facing on Windows? Specifically, any advice on handling the missing libraries and platform-specific code would be invaluable.

Thank you once again for your time and support. I look forward to any advice you can offer to help move this project forward.

**Comment by AloneLiberty** [comment]
Compiling under Windows is such mess thing, there is a lot of required steps in https://github.com/AloneLiberty/FlipperNestedRecovery/blob/dev/.github/workflows/build.yml
Easier for you will be fork this repository, make changes, remove upload_pypi from actions script and let it compile everything for you. I'm not familiar with PyInstaller and how it handles build script, so unfortunately can't help you to write anything for it. If you still want to compile library on Windows by yourself and steps from build workflow won't help you - contact me via Telegram https://t.me/libertydev and I will help you figure what went wrong

**Comment by oldip** [comment]
> Compiling under Windows is such mess thing, there is a lot of required steps in https://github.com/AloneLiberty/FlipperNestedRecovery/blob/dev/.github/workflows/build.yml Easier for you will be fork this repository, make changes, remove upload_pypi from actions script and let it compile everything for you. I'm not familiar with PyInstaller and how it handles build script, so unfortunately can't help you to write anything for it. If you still want to compile library on Windows by yourself and steps from build workflow won't help you - contact me via Telegram https://t.me/libertydev and I will help you figure what went wrong

Hi AloneLiberty,

Thank you for your guidance! I successfully compiled the GUI version of the project. You can check it out here: [FlipperNestedRecovery-GUI](https://github.com/oldip/FlipperNestedRecovery-GUI).

Feel free to provide any feedback or suggestions.
