### ISSUE TITLE
Feat. request: Cracking of files without connecting to F0

### ISSUE THREAD

**Issue by Luk164** [AloneLiberty/FlipperNestedRecovery#3]
I would like to ask if it would be possible to add a way to crack files manually extracted from F0 by other means. This would be useful especially for brute-forcing, as we could extract the data, upload to a more powerful machine like a server and leave the bruteforce running without needing F0 to be connected. Once done there would be some sort of output file or just a list of found keys in terminal to load onto flipper.

I already took a look at implementing it myself but it has been years since I touched C and I rarely use python as well so I feel out of my element a little. I may keep working on it by myself along with trying to see if I could use GPU to accelerate the cracking, maybe I will just write my own tool in a different lang though.

**Comment by Luk164** [comment]
Update: I noticed the --file switch but it does not seem to be working for me. with this command `FlipperNested.exe --progress --preserve --file .\312CFE0B.nonces` I get the following output:

```
Traceback (most recent call last):
  File "C:\Users\me\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\me\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\miniconda3\Scripts\FlipperNested.exe\__main__.py", line 7, in <module>
  File "C:\Users\me\miniconda3\lib\site-packages\FlipperNested\cli.py", line 17, in main
    flipper.run(args)
  File "C:\Users\me\miniconda3\lib\site-packages\FlipperNested\main.py", line 45, in run
    self.extract_nonces_from_file(args.file)
  File "C:\Users\me\miniconda3\lib\site-packages\FlipperNested\main.py", line 152, in extract_nonces_from_file
    if not self.parse_file(file.read()):
  File "C:\Users\me\miniconda3\lib\site-packages\FlipperNested\main.py", line 78, in parse_file
    value = self.connection.file_read(values[1])
AttributeError: 'NoneType' object has no attribute 'file_read'
```

**Comment by AloneLiberty** [comment]
You can save files on your PC with --save, --preserve won't delete them on Flipper after recovery. Then load via --file 0_0.nonces (not UID.nonces for HardNested)

**Comment by AloneLiberty** [comment]
HardNested should not take more than 10 minutes, if it takes more - this is bug. If you got this bug, please create Issue and upload your nonces to it (full .nested folder)

**Comment by Luk164** [comment]
@AloneLiberty Thx for the reply. It was taking hours and was not even close to being finished so I wanted to have it run somewhere else. I will create a new issue with the files attached. BTW I already created a small modification in my fork so I could use UID.nonces before you replied. Take a look if you wish
