### ISSUE TITLE
Unable to Install on Windows

### ISSUE THREAD

**Issue by corysabol** [AloneLiberty/FlipperNestedRecovery#7]
I'm wondering if this is supported on Windows.
I'm receiving issues with the pthread.h dependency. 
I've seemingly installed it using vcpkg and configured it to be available to the MSVC build tools, but installing this package still fails with the following error:

```
 NestedSolver/library.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

Any idea what might be causing this issue? If the solution is to "just use linux" then I'll do that, lol.

**Comment by AloneLiberty** [comment]
You can't just compile it easily on Windows. Check how it's done GitHub workflows. Also there should be precompiled ones for all supported versions (3.8-3.11).

**Comment by corysabol** [comment]
D'oh I didn't realize I had my global python version set to 3.12.x which is why pip tried to build it rather than grabbing a pre-built. Looks like it's good to go now. Thanks for the quick reply 😄
